version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: truescan_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb+srv://mahtotgher13:PWfDXhkoJreTmqPl@cluster0.aphrypq.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
